jqassistant:
  plugins:
    - group-id: net.aschemann.jqassistant.plugins
      artifact-id: jqa-groovy-plugin
      version: 0.2.0-SNAPSHOT
    - group-id: de.kontext-e.jqassistant.plugin
      artifact-id: jqassistant.plugin.git
      version: 2.4.0
  scan:
    continue-on-error: true
    # We need this with the Maven scanner as it only scans target/ by default
    include:
      files:
        - .git
    properties:
      directory.follow-symbolic-links: true
      maven3.dependencies.scan: true
  analyze:
    rule:
      directory: jqassistant/rules/
    report:
      fail-on-severity: blocker