<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.open-elements.support-and-care.maven</groupId>
    <artifactId>full-repo-investigator</artifactId>
    <version>0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>com.buschmais.jqassistant</groupId>
                <artifactId>jqassistant-maven-plugin</artifactId>
                <version>2.7.0</version> <!-- Adjust to the latest version -->
                <executions>
                    <execution>
                        <phase>verify</phase>
                        <goals>
                            <goal>scan</goal>
                        </goals>
                    </execution>
                </executions>
<!--                <configuration>-->
<!--                    <configurationLocations>-->
<!--                        <configurationLocation>${project.basedir}/.jqassistant.yaml</configurationLocation>-->
<!--                    </configurationLocations>-->
<!--                </configuration>-->
            </plugin>
            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <sourceDirectory>src/docs</sourceDirectory>
                    <preserveDirectories>true</preserveDirectories>
                    <attributes>
                        <doctype>book</doctype>
                        <toc>left</toc>
                        <icons>font</icons>
                        <jqassistant-report-path>
                            ${project.build.directory}/jqassistant/jqassistant-report.xml
                        </jqassistant-report-path>
                        <!--                        <jqassistant-templates-path>-->
                        <!--                            your-custom-template-jar-or-folder-name-->
                        <!--                        </jqassistant-templates-path>-->
                        <!--                        <imagesDir>-->
                        <!--                            your-desired-folder-to-store-pictures-inside-your-output-directory -->
                        <!--                        </imagesDir>-->
                        <kroki-server-url>https://kroki.io</kroki-server-url>
                        <kroki-default-format>svg</kroki-default-format>
                    </attributes>
                    <requires>
                        <require>asciidoctor-diagram</require>
                    </requires>
                </configuration>
                <executions>
                    <execution>
                        <id>output-html</id>
                        <!--                        <phase>site</phase>-->
                        <phase>verify</phase>
                        <goals>
                            <goal>process-asciidoc</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctorj-diagram</artifactId>
                        <version>2.2.3</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jqassistant.tooling.asciidoctorj</groupId>
                        <artifactId>jqassistant-asciidoctorj-extensions</artifactId>
                        <version>1.1.0</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>