= Maven Support & Care Tools
:icons: font
:toc: left

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This repository contains a collection of tools and scripts to support the maintenance and care of Maven projects.

== Prerequisites

=== Check out Maven source code

// further documentation: https://github.com/apache/maven-sources

Follow the instructions in https://maven.apache.org/scm.html[Maven SCM documentation] to check out Maven to this directory.

=== Further needed tools

If you want to build Maven, you have to install a JDK 21 and Maven 3.9.9.

[TIP]
====
https://sdkman.io/[SDKMAN!], a Software Development Kit Manager, helps to install and managing JDKs and Maven version on your machine.
====

Some tests are using https://java.testcontainers.org/[Testcontainers].
This library needs https://docs.docker.com/engine/[Docker Engine] to run properly.

https://github.com/diffplug/spotless[Spotless] Plugin needs https://www.npmjs.com/[NPM] during the build.
Therefore, also NPM is needed.

[TIP]
====
https://github.com/nvm-sh/nvm[NVM], a Node Version Manager, helps to install and managing Node and NPM versions on your machine.
====

== Common Tools

You can execute some of the following tools from the root directory of this repository with the repo command, e.g.,

[source,bash]
----
repo forall -c "${PWD}/bin/gh-subscribe"
----

Note that it is necessary to provide the full path to the script
to execute it in each repository as the `repo` command changes the working directory.

[TIP]
====
Using the `-r` switch, you can execute the command on a subset of repositories only, e.g.,

[source,bash]
.Execute the command only on the core repositories
----
repo forall -r 'core' -c "${PWD}/bin/gh-subscribe"
----
====

The following tools are available in the `bin` directory (and have inherent documentation).

* link:bin/gh-subscribe[gh-subscribe] - Subscribe to a GitHub repository (watch).
+
Execute with the `repo` command.
* link:bin/run-maven[run-maven] - Execute Maven goals for multiple projects.
+
Execute without the `repo` command (define target projects in the `PROJECTS` environment variable).
+
As we intended this script for mass execution of many Maven projects and respective error tracking,
it only shows minimal output (essentially success or failure, and a count of the Maven projects to proceed).
The script writes more output to log files in the link:logs[`logs`] directory.
Each execution will generate a new log file (in a respective subdirectory for each project).
+
[CAUTION]
====
This script adds https://gradle.com/develocity/[Develocity]
by configuring the respective link:develocity/extensions.xml[Maven extension] for all projects.

If you want to make use of it, you have to set the environment variable `USE_DEVELOCITY` to `true`.
This will automatically link:develocity/develocity.xml[accept upload permissions] *on your behalf*.
Whenever you execute Maven projects,
you will afterward find a report in Develocity (link will be published in the respective link:logs[`logs`] output).
====