name: Run Maven (reactor) build with all components

on:
  push:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to initialize repo with (use default branch if empty)'
        required: false
        default: ''

jobs:
  maven-reactor-build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        distribution: [ 'zulu' ]
        jdk: [ '21' ] # [ '11', '17', ]
        maven-version: [ '3.9.9', '4.0.0-rc-2' ]

    env:
      BRANCH: "${{ github.event.inputs.branch || github.ref_name }}"
      GITHUB_ORGANIZATION: "${{ github.repository_owner }}"

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: ${{ matrix.jdk }}
          java-distribution: ${{ matrix.distribution }}
          maven-version: ${{ matrix.maven-version }}

      - name: Show current Maven version
        run: mvn --version

      - name: Install repo tool
        run: |
          sudo apt-get update
          sudo apt-get install -y repo

      - name: Initialize repo
        run: ./bin/repo-start

      - name: Switch to special branches
        run: ./bin/repo-checkout-specific-branches

      - name: Build with Maven
        env:
          PROJECTS: "sources/aggregator"
          USE_DEVELOCITY: true
          FAIL_FAST: true
          PREVIEW_LOGLINES: 50
        run: ./bin/run-maven clean install site -fae -Dsurefire.rerunFailingTestsCount=2

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always() # Ensure this step runs even if the previous steps fail
        with:
          name: maven-reactor-site
          path: sources/aggregator/target/site

      - name: Upload Site
        uses: actions/upload-artifact@v4
        if: always() # Ensure this step runs even if the previous steps fail
        with:
          name: build-logs
          path: logs
