name: Run Maven build of all components

on:
  schedule:
    # only runs on the main branch (see below)
    - cron: '0 3 * * *'
  push:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to initialize repo with (use default branch if empty)'
        required: false
        default: ''
      projects:
        description: 'Space-separated list of projects to process'
        required: false
        default: ''
      debug:
        description: 'Enable debug mode (finally the same as debug checkbox but settable via "gh" CLI/API'
        required: false
        type: boolean
        default: false

permissions:
  packages: read
  issues: read
  pull-requests: read
  contents: write
  
jobs:
  maven-all-projects-build:
    # Run the job if:
    # - It's triggered via schedule, only if on the main branch
    # - Or if it's triggered by a push (any branch) or workflow_dispatch (any branch)
    if: ${{ github.event_name != 'schedule' || github.ref == 'refs/heads/main' }}
    runs-on: self-hosted

    env:
      BRANCH: "${{ github.event.inputs.branch || github.ref_name }}"
      GITHUB_ORGANIZATION: "${{ github.repository_owner }}"
      GITHUB_LOGIN: ${{ github.repository_owner }}
      GITHUB_TOKEN: ${{ github.token }}
      GITHUB_OAUTH: ${{ github.token }}
      PROJECTS: ${{ github.event.inputs.projects }}
      ACTIONS_RUNNER_DEBUG: ${{ github.event.inputs.debug }}
      ACTIONS_STEP_DEBUG: ${{ github.event.inputs.debug }}

    steps:
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: "21"
          java-distribution: "zulu"
          maven-version: "3.9.11"

      - name: Show current Maven version
        run: mvn --version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Verify npm installation
        run: npm --version

      - name: Install repo tool
        run: |
          sudo apt-get update
          sudo apt-get install -y repo

      - name: Initialize repo
        run: ./bin/repo-start

      - name: Switch to special branches
        run: ./bin/repo-checkout-specific-branches

      - name: Build with Maven
        env:
          USE_DEVELOCITY: true
          PREVIEW_LOGLINES: 50
        run: ./bin/run-maven clean install -fae -Dsurefire.rerunFailingTestsCount=2 2>&1 | tee logs/maven-log

      - name: Run jQAssistant Scan
        env:
          USE_DEVELOCITY: true
          PREVIEW_LOGLINES: 50
        run: ./bin/run-jqa scan 2>&1 | tee logs/jqa-scan.log

      - name: Upload jqassistant/store artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jqassistant-store-scan
          path: jqassistant/store

      - name: Collect Git status and environment
        if: always()
        run: |
          (
            echo "Git:"
            git status
            echo "Env:"
            env | sort
            echo "PWD:"
            pwd
          ) 2>&1 | tee logs/env.log 

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs-all-projects
          path: logs

  maven-jqa-github-scan:
    # Run the job if:
    # - It's triggered via schedule, only if on the main branch
    # - Or if it's triggered by a push (any branch) or workflow_dispatch (any branch)
    if: ${{ github.event_name != 'schedule' || github.ref == 'refs/heads/main' }}
    runs-on: self-hosted
    needs: maven-all-projects-build

    env:
      BRANCH: "${{ github.event.inputs.branch || github.ref_name }}"
      GITHUB_ORGANIZATION: "${{ github.repository_owner }}"
      GITHUB_LOGIN: ${{ github.repository_owner }}
      GITHUB_TOKEN: ${{ github.token }}
      GITHUB_OAUTH: ${{ github.token }}
      PROJECTS: ${{ github.event.inputs.projects }}
      ACTIONS_RUNNER_DEBUG: ${{ github.event.inputs.debug }}
      ACTIONS_STEP_DEBUG: ${{ github.event.inputs.debug }}

    steps:
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: "21"
          java-distribution: "zulu"
          maven-version: "3.9.11"

      - name: Show current Maven version
        run: mvn --version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Verify npm installation
        run: npm --version

      - name: Install repo tool
        run: |
          sudo apt-get update
          sudo apt-get install -y repo

      - name: Initialize repo
        run: ./bin/repo-start

      - name: Switch to special branches
        run: ./bin/repo-checkout-specific-branches

      - name: Download jqassistant/store artifact
        uses: actions/download-artifact@v4
        with:
          name: jqassistant-store-scan
          path: jqassistant/store

      - name: Run jQAssistant GitHub Scan
        env:
          USE_DEVELOCITY: true
          PREVIEW_LOGLINES: 50
        run: ./bin/run-jqa github 2>&1 | tee logs/jqa-github.log

      - name: Upload jqassistant/store artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jqassistant-store-full
          path: jqassistant/store

      - name: Collect Git status and environment
        if: always()
        run: |
          (
            echo "Git:"
            git status
            echo "Env:"
            env | sort
            echo "PWD:"
            pwd
          ) 2>&1 | tee logs/env.log 

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs-jqa-github-scan
          path: logs

  maven-jqa-analyze:
    # Run the job if:
    # - It's triggered via schedule, only if on the main branch
    # - Or if it's triggered by a push (any branch) or workflow_dispatch (any branch)
    if: ${{ github.event_name != 'schedule' || github.ref == 'refs/heads/main' }}
    runs-on: self-hosted
    needs: maven-jqa-github-scan

    env:
      BRANCH: "${{ github.event.inputs.branch || github.ref_name }}"
      GITHUB_ORGANIZATION: "${{ github.repository_owner }}"
      GITHUB_LOGIN: ${{ github.repository_owner }}
      GITHUB_TOKEN: ${{ github.token }}
      GITHUB_OAUTH: ${{ github.token }}
      PROJECTS: ${{ github.event.inputs.projects }}
      ACTIONS_RUNNER_DEBUG: ${{ github.event.inputs.debug }}
      ACTIONS_STEP_DEBUG: ${{ github.event.inputs.debug }}

    steps:
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: "21"
          java-distribution: "zulu"
          maven-version: "3.9.11"

      - name: Show current Maven version
        run: mvn --version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Verify npm installation
        run: npm --version

      - name: Install repo tool
        run: |
          sudo apt-get update
          sudo apt-get install -y repo

      - name: Initialize repo
        run: ./bin/repo-start

      - name: Switch to special branches
        run: ./bin/repo-checkout-specific-branches

      - name: Download jqassistant/store artifact
        uses: actions/download-artifact@v4
        with:
          name: jqassistant-store-full
          path: jqassistant/store

      - name: Run jQAssistant Analyze
        env:
          USE_DEVELOCITY: true
          PREVIEW_LOGLINES: 50
        run: ./bin/run-jqa analyze 2>&1 | tee logs/jqa-analyze.log

      - name: Upload generated documentation
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: generated-docs
          path: target/generated-docs

      - name: Collect Git status and environment
        if: always()
        run: |
          (
            echo "Git:"
            git status
            echo "Env:"
            env | sort
            echo "PWD:"
            pwd
          ) 2>&1 | tee logs/env.log 

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs-jqa-analyze
          path: logs

  deploy-to-netlify:
    name: 'Deploy to Netlify Preview'
    runs-on: self-hosted
    if: github.ref != 'refs/heads/main'
    needs: maven-jqa-analyze

    steps:
      - uses: actions/checkout@v3

      # Netlify needs NPM/Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Verify npm installation
        run: npm --version

      - name: Download generated documentation
        uses: actions/download-artifact@v4
        with:
          name: generated-docs
          path: target/generated-docs

      # Sets the branch name as an environment variable
      - uses: nelonoel/branch-name@v1.0.1

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: false
          NETLIFY_DEPLOY_MESSAGE: "Preview deploy from GitHub Actions"
          BRANCH: ${{ env.BRANCH_NAME }}
        with:
          publish-dir: target/generated-docs
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
